import { addDoc, collection } from "firebase/firestore";
import db from "../db/dbFirebase.js";

const products = [
    // Ciencia Ficción
    {
        id: "6",
        title: "Dune",
        price: "6899.99",
        description: "Una épica historia sobre poder, traición y destino en un planeta desértico.",
        autor: "Frank Herbert",
        genre: "Ciencia Ficción",
        pages: "688",
        idiom: "Español",
        editorial: "Debolsillo",
        image: "https://ia801601.us.archive.org/view_archive.php?archive=/25/items/m_covers_0014/m_covers_0014_63.zip&file=0014636513-M.jpg",
        stock: 28,
        publication: "2021-11-15",
    },
    {
        id: "7",
        title: "El fin de la infancia",
        price: "3999.99",
        description: "Los humanos enfrentan una civilización avanzada que cambia su destino.",
        autor: "Arthur C. Clarke",
        genre: "Ciencia Ficción",
        pages: "320",
        idiom: "Español",
        editorial: "Planeta",
        image: "https://ia801601.us.archive.org/view_archive.php?archive=/25/items/m_covers_0014/m_covers_0014_11.zip&file=0014119888-M.jpg",
        stock: 22,
        publication: "2022-07-22",
    },
    {
        id: "8",
        title: "Neuromante",
        price: "4699.99",
        description: "Un pionero del género ciberpunk que mezcla tecnología y humanos en una oscura narrativa.",
        autor: "William Gibson",
        genre: "Ciencia Ficción",
        pages: "320",
        idiom: "Español",
        editorial: "Minotauro",
        image: "https://covers.openlibrary.org/b/id/7257789-M.jpg",
        stock: 15,
        publication: "2023-03-18",
    },
    {
        id: "9",
        title: "El juego de Ender",
        price: "4199.99",
        description: "La historia de un joven prodigio que debe salvar a la humanidad de una invasión alienígena.",
        autor: "Orson Scott Card",
        genre: "Ciencia Ficción",
        pages: "352",
        idiom: "Español",
        editorial: "Ediciones B",
        image: "https://covers.openlibrary.org/b/id/14532809-M.jpg",
        stock: 27,
        publication: "2023-05-01",
    },
    {
        id: "10",
        title: "La guerra interminable",
        price: "4499.99",
        description: "Una visión épica del futuro de la guerra espacial y sus efectos sobre los soldados.",
        autor: "Joe Haldeman",
        genre: "Ciencia Ficción",
        pages: "336",
        idiom: "Español",
        editorial: "Alamut",
        image: "https://covers.openlibrary.org/b/id/13245196-M.jpg",
        stock: 17,
        publication: "2022-10-10",
    },

    // Misterio
    {
        id: "26",
        title: "Los crímenes de la calle Morgue",
        price: "4199.99",
        description: "El primer relato de detectives de la historia, donde Dupin investiga un macabro asesinato.",
        autor: "Edgar Allan Poe",
        genre: "Misterio",
        pages: "64",
        idiom: "Español",
        editorial: "Alianza Editorial",
        image: "https://covers.openlibrary.org/b/id/13674864-M.jpg",
        stock: 19,
        publication: "2024-02-15",
    },
    {
        id: "27",
        title: "El asesinato de Roger Ackroyd",
        price: "5499.99",
        description: "Un clásico de Agatha Christie donde Poirot debe resolver un caso complicado.",
        autor: "Agatha Christie",
        genre: "Misterio",
        pages: "288",
        idiom: "Español",
        editorial: "Debolsillo",
        image: "https://covers.openlibrary.org/b/id/14586509-M.jpg",
        stock: 14,
        publication: "2023-11-25",
    },
    {
        id: "28",
        title: "El guardián invisible",
        price: "5799.99",
        description: "Un thriller donde una inspectora debe resolver crímenes en el País Vasco.",
        autor: "Dolores Redondo",
        genre: "Misterio",
        pages: "400",
        idiom: "Español",
        editorial: "Destino",
        image: "https://covers.openlibrary.org/b/id/8908662-M.jpg",
        stock: 21,
        publication: "2024-03-01",
    },
    {
        id: "29",
        title: "El misterio de la guía de ferrocarriles",
        price: "5099.99",
        description: "Un enigma donde Hercule Poirot sigue a un asesino en serie que sigue una guía de trenes.",
        autor: "Agatha Christie",
        genre: "Misterio",
        pages: "256",
        idiom: "Español",
        editorial: "Debolsillo",
        image: "https://covers.openlibrary.org/b/id/11362674-M.jpg",
        stock: 23,
        publication: "2024-01-30",
    },
    {
        id: "30",
        title: "El secreto de las siete semillas",
        price: "4299.99",
        description: "Un empresario busca el equilibrio espiritual mientras resuelve un misterio.",
        autor: "David Fischman",
        genre: "Misterio",
        pages: "208",
        idiom: "Español",
        editorial: "Grupo Planeta",
        image: "https://covers.openlibrary.org/b/id/3358959-M.jpg",
        stock: 30,
        publication: "2023-12-10",
    },

    // Romance
    {
        id: "31",
        title: "Culpa mía",
        price: "5899.99",
        description: "Una historia de amor prohibido entre dos jóvenes de mundos opuestos.",
        autor: "Mercedes Ron",
        genre: "Romance",
        pages: "368",
        idiom: "Español",
        editorial: "Montena",
        image: "https://ia600505.us.archive.org/view_archive.php?archive=/25/items/m_covers_0010/m_covers_0010_51.zip&file=0010512957-M.jpg",
        stock: 16,
        publication: "2024-03-25",
    },
    {
        id: "32",
        title: "Te daría el mundo",
        price: "4599.99",
        description: "La historia de dos gemelos que enfrentan la vida, el amor y la pérdida.",
        autor: "Jandy Nelson",
        genre: "Romance",
        pages: "368",
        idiom: "Español",
        editorial: "Puck",
        image: "https://covers.openlibrary.org/b/id/14060439-M.jpg",
        stock: 18,
        publication: "2024-02-10",
    },
    {
        id: "33",
        title: "Orgullo y prejuicio",
        price: "4899.99",
        description: "Una de las novelas románticas más célebres, que cuenta la historia de amor entre Elizabeth Bennet y Mr. Darcy.",
        autor: "Jane Austen",
        genre: "Romance",
        pages: "432",
        idiom: "Español",
        editorial: "Alianza Editorial",
        image: "https://covers.openlibrary.org/b/id/11104197-M.jpg",
        stock: 24,
        publication: "2023-11-10",
    },
    {
        id: "34",
        title: "La chica del tren",
        price: "5999.99",
        description: "Un thriller romántico que explora las relaciones y las decisiones fatales.",
        autor: "Paula Hawkins",
        genre: "Romance",
        pages: "392",
        idiom: "Español",
        editorial: "Planeta",
        image: "https://covers.openlibrary.org/b/id/7395624-M.jpg",
        stock: 12,
        publication: "2024-04-05",
    },
    {
        id: "35",
        title: "A todos los chicos de los que me enamoré",
        price: "3999.99",
        description: "La vida de Lara Jean cambia cuando sus cartas de amor secretas se envían.",
        autor: "Jenny Han",
        genre: "Romance",
        pages: "368",
        idiom: "Español",
        editorial: "Planeta",
        image: "https://covers.openlibrary.org/b/id/12339443-M.jpg",
        stock: 13,
        publication: "2024-05-01",
    },
    {
        id: "36",
        title: "Bajo la misma estrella",
        price: "5099.99",
        description: "Un conmovedor romance entre dos adolescentes que luchan contra el cáncer.",
        autor: "John Green",
        genre: "Romance",
        pages: "304",
        idiom: "Español",
        editorial: "Nube de Tinta",
        image: "https://covers.openlibrary.org/b/id/13567848-M.jpg",
        stock: 11,
        publication: "2024-01-15",
    },

    // Comedia
    {
        id: "46",
        title: "Los hombres son de Marte, las mujeres son de Venus",
        price: "3499.99",
        description: "Una guía humorística sobre las diferencias entre hombres y mujeres.",
        autor: "John Gray",
        genre: "Comedia",
        pages: "320",
        idiom: "Español",
        editorial: "Grijalbo",
        image: "https://covers.openlibrary.org/b/id/13302534-M.jpg",
        stock: 26,
        publication: "2024-02-18",
    },
    {
        id: "47",
        title: "Cuentos de la selva",
        price: "2999.99",
        description: "Historias humorísticas de la vida salvaje y sus habitantes.",
        autor: "Horacio Quiroga",
        genre: "Comedia",
        pages: "160",
        idiom: "Español",
        editorial: "Alfaguara",
        image: "https://covers.openlibrary.org/b/id/9280912-M.jpg",
        stock: 25,
        publication: "2024-01-11",
    },
    {
        id: "48",
        title: "Sin noticias de Gurb",
        price: "3999.99",
        description: "Una novela divertida sobre la búsqueda de un alienígena perdido en la Barcelona pre-olímpica.",
        autor: "Eduardo Mendoza",
        genre: "Comedia",
        pages: "144",
        idiom: "Español",
        editorial: "Seix Barral",
        image: "https://covers.openlibrary.org/b/id/8377894-M.jpg",
        stock: 20,
        publication: "2024-04-12",
    },
    {
        id: "49",
        title: "La conjura de los necios",
        price: "5799.99",
        description: "Una hilarante y satírica novela sobre las desventuras de un hombre excéntrico y malhumorado.",
        autor: "John Kennedy Toole",
        genre: "Comedia",
        pages: "416",
        idiom: "Español",
        editorial: "Anagrama",
        image: "https://covers.openlibrary.org/b/id/9155681-M.jpg",
        stock: 9,
        publication: "2024-03-07",
    },
    {
        id: "50",
        title: "Wilt",
        price: "3499.99",
        description: "Un profesor insatisfecho y su absurda serie de desgracias y malentendidos.",
        autor: "Tom Sharpe",
        genre: "Comedia",
        pages: "336",
        idiom: "Español",
        editorial: "Anagrama",
        image: "https://covers.openlibrary.org/b/id/12365382-M.jpg",
        stock: 7,
        publication: "2024-05-22",
    },
    
    // Drama
    {
        id: "51",
        title: "Cien años de soledad",
        price: "6999.99",
        description: "Una de las obras más importantes de la literatura latinoamericana, que narra la historia de la familia Buendía a lo largo de varias generaciones.",
        autor: "Gabriel García Márquez",
        genre: "Drama",
        pages: "496",
        idiom: "Español",
        editorial: "Debolsillo",
        image: "https://covers.openlibrary.org/b/id/11090890-M.jpg",
        stock: 27,
        publication: "2024-02-10",
    },
    {
        id: "52",
        title: "El guardián entre el centeno",
        price: "4599.99",
        description: "Una novela que sigue las experiencias de Holden Caulfield, un joven rebelde y desencantado con la sociedad.",
        autor: "J.D. Salinger",
        genre: "Drama",
        pages: "240",
        idiom: "Español",
        editorial: "Alianza Editorial",
        image: "https://covers.openlibrary.org/b/id/9123456-M.jpg",
        stock: 13,
        publication: "2023-12-15",
    },
    {
        id: "53",
        title: "Madame Bovary",
        price: "4999.99",
        description: "La historia de Emma Bovary, una mujer que busca escapar de la monotonía de la vida provincial francesa.",
        autor: "Gustave Flaubert",
        genre: "Drama",
        pages: "432",
        idiom: "Español",
        editorial: "Cátedra",
        image: "https://covers.openlibrary.org/b/id/9876543-M.jpg",
        stock: 18,
        publication: "2024-03-20",
    },
    {
        id: "54",
        title: "Los miserables",
        price: "8499.99",
        description: "Una obra monumental que narra la historia de varios personajes en la Francia post-revolucionaria, centrada en la redención de Jean Valjean.",
        autor: "Victor Hugo",
        genre: "Drama",
        pages: "1440",
        idiom: "Español",
        editorial: "Edhasa",
        image: "https://covers.openlibrary.org/b/id/1234567-M.jpg",
        stock: 5,
        publication: "2023-11-05",
    },
    {
        id: "55",
        title: "Anna Karenina",
        price: "6299.99",
        description: "Un profundo análisis de la sociedad rusa a través del trágico destino de Anna Karenina.",
        autor: "León Tolstói",
        genre: "Drama",
        pages: "864",
        idiom: "Español",
        editorial: "Penguin Clásicos",
        image: "https://covers.openlibrary.org/b/id/10123456-M.jpg",
        stock: 12,
        publication: "2024-01-25",
    }
];

const seedProducts = () => {
    const productsRef = collection(db, "products")
    products.map(( {id, ...dataProduct } ) => {
        addDoc(productsRef, dataProduct)
    })
    return
}

console.log('Productos subidos')

seedProducts()